#!/usr/bin/env bash

#apt-get update -y
#apt-get install -y nginx
#echo "Hello World!" > /var/www/html/index.html
#service nginx start
!/bin/bash
set -e
apt-get update
apt-get install -y nginx
mkdir -p /var/www/html/
echo "Hello World!" > /var/www/html/index.html
service nginx start