#!/usr/bin/env bash
# Install Nginx Web Server and configure a custom index page

# Exit if any command fails
set -e

# Update package index
sudo apt-get update -y

# Install nginx
sudo apt-get install nginx -y

# Overwrite index page with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Restart nginx using service (not systemctl)
sudo service nginx restart
