#!/usr/bin/env bash
# This script installs Nginx and configures a 301 redirection for /redirect_me

apt-get update -y
apt-get install nginx -y

sed -i '/listen 80 default_server;/a \ \n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

service nginx restart