#!/usr/bin/env bash
# This script installs Nginx and configures a custom 404 page

apt-get update -y
apt-get install nginx -y

echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

sed -i '/listen 80 default_server;/a \ \n\terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default

service nginx restart