#!/usr/bin/env bash
# Configures UFW to block all incoming traffic except ports 22, 80, and 443

apt-get update -y
apt-get install ufw -y

ufw default deny incoming
ufw default allow outgoing
ufw allow 22
ufw allow 80
ufw allow 443
ufw --force enable